project:
  type: website
  output-dir: docs
execute:
  freeze: true
website:
  title: "Isaac Flath"
  open-graph:
    locale: en_US
  twitter-card:
    image: street.jpg
    creator: "@isaac_flath"
  site-url: https://maven.com/kentro/context-engineering-for-coding
  description: "One Stop Shop for Information on Context Engineering for Coding"
  navbar:
    right:
      - text: "Tool Reviews"
        file: tool-reviews.qmd
      - text: "Guides"
        file: guides.qmd
  page-footer: 
    left: "Isaac Flath" 
    right: 
      - icon: linkedin
        text: LinkedIn
        href: https://linkedin.com/in/isaacflath/
      - icon: github
        text: Github
        href: https://github.com/kentro-tech
      - icon: twitter
        text: Twitter
        href: https://twitter.com/isaac_flath
format:
  html:
    theme: 
      light: cosmo
      dark: cyborg