project:
  type: website
  output-dir: docs
execute:
  freeze: true
website:
  title: "Isaac Flath"
  site-url: https://ai-context-engineering.com
  description: "One Stop Shop for Information on Context Engineering for Coding"
  open-graph:
    locale: en_US
    site-name: "Isaac Flath - AI Context Engineering"
    image: static/default-social.png
  twitter-card:
    card-style: summary_large_image
    image: static/default-social.png
    creator: "@isaac_flath"
    site: "@isaac_flath"
  navbar:
    right:
      - text: "Tool Reviews"
        file: tool-reviews.qmd
      - text: "Guides"
        file: guides.qmd
  page-footer: 
    left: "Isaac Flath" 
    right: 
      - icon: linkedin
        text: LinkedIn
        href: https://linkedin.com/in/isaacflath/
      - icon: github
        text: Github
        href: https://github.com/kentro-tech
      - icon: twitter
        text: Twitter
        href: https://twitter.com/isaac_flath
format:
  html:
    theme: 
      light: cosmo
      dark: cyborg